Sisjuri/Models/perfil.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisjuri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil
    {
        public perfil()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int id_perfil { get; set; }
        public string nome_perfil { get; set; }
        public string descricao_perfil { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
    }
}

Sisjuri/Controllers/PerfilController.cs
using Sisjuri.Models;
using Sisjuri.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sisjuri.Controllers
{
    public class PerfilController : BaseController
    {
        private PerfilRepository _PerfilRepository;

        public PerfilRepository PerfilRepository
        {
            get {
                if (_PerfilRepository == null)
                    _PerfilRepository = new PerfilRepository();
                return _PerfilRepository; }
            set { _PerfilRepository = value; }
        }


        //
        // GET: /Perfil/
        public ActionResult Index()
        {
            return View(new perfil());
        }

        // /Perfil/List
        public ActionResult List(perfil entity, String message)
        {
            ViewData["message"] = message;
            if (string.IsNullOrEmpty(entity.nome_perfil))
            {
                return View(PerfilRepository.GetAll());
            }
            else
            {
                return View(PerfilRepository.GetAllByCriteria(entity.nome_perfil));
            }
        }

        //
        // GET: /Perfil/Details/5
        public ActionResult Details(int id)
        {
            return View(PerfilRepository.GetOne(id));
        }

        //
        // GET: /Perfil/Create
        public ActionResult Create()
        {
            return View(new perfil());
        }

        //
        // POST: /Perfil/Create
        [HttpPost]
        public ActionResult Create(perfil perfil)
        {
            try
            {
                if (validate(perfil))
                    return View(perfil);
                PerfilRepository.Create(perfil);

                return RedirectToAction("List", new { message = "Dados cadastrados com sucesso!" });
            }
            catch
            {
                return View(perfil);
            }
        }

        //
        // GET: /Perfil/Edit/5
        public ActionResult Edit(int id)
        {
            return View(PerfilRepository.GetOne(id));
        }

        //
        // POST: /Perfil/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, perfil perfil)
        {
            try
            {
                if (validate(perfil))
                    return View(perfil);
                PerfilRepository.Edit(perfil);
                return RedirectToAction("List", new { message = "Dados editados com sucesso!" });
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Perfil/Delete/5
        public ActionResult Delete(int id)
        {
            return View(PerfilRepository.GetOne(id));
        }

        //
        // POST: /Perfil/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, perfil perfil)
        {
            try
            {
                perfil = PerfilRepository.GetOne(id);
                PerfilRepository.Delete(perfil);

                return RedirectToAction("List", new { message = "Dados excluídos com sucesso!" });
            }
            catch
            {
                return View();
            }
        }

        public bool validate(perfil entity)
        {
            bool retorno = false;

            if (string.IsNullOrEmpty(entity.nome_perfil))
            {
                ModelState.AddModelError("nome_perfil", "Campo obrigatório");
                retorno = true;
            }
            if (string.IsNullOrEmpty(entity.descricao_perfil))
            {
                ModelState.AddModelError("descricao_perfil", "Campo obrigatório");
                retorno = true;
            }

            return retorno;
        }

    }
}

Sisjuri/Views/Perfil/Create.cshtml
@model Sisjuri.Models.perfil

@{
    ViewBag.Title = "Cadastrar perfil";
}

<h1>Cadastrar</h1>
<div class="row">
    <div class="main-box">
        <h2>Novo perfil</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.nome_perfil, "Nome do perfil", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.nome_perfil, new { size = 30, maxlength = 30 })
                        @Html.ValidationMessageFor(model => model.nome_perfil)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.descricao_perfil, "Descrição do perfil", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.descricao_perfil, new { cols = 50, rows = 4 })
                        @Html.ValidationMessageFor(model => model.descricao_perfil)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Cadastrar" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        <div>
            @Html.ActionLink("Pesquisar perfis", "Index") | @Html.ActionLink("Voltar à lista", "List")
        </div>
    </div>
</div>

Sisjuri/Views/Perfil/Delete.cshtml
@model Sisjuri.Models.perfil

@{
    ViewBag.Title = "Excluir perfil";
}

<h1>Excluir</h1>
<div class="row">
    <div class="main-box">
        <h4>Você tem certeza que deseja excluir este perfil?</h4>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.LabelFor(model => model.nome_perfil, "Nome do perfil")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.nome_perfil)
                </dd>

                <dt>
                    @Html.LabelFor(model => model.descricao_perfil, "Descrição do perfil")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.descricao_perfil)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Excluir" class="btn btn-default" /> |
                    @Html.ActionLink("Voltar à lista", "Index")
                </div>
            }
        </div>
    </div>
</div>

Sisjuri/Views/Perfil/Details.cshtml
@model Sisjuri.Models.perfil

@{
    ViewBag.Title = "Detalhes do perfil";
}

<h1>Detalhes</h1>
<div class="row">
    <div class="main-box">
        <h2>Perfil</h2>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.LabelFor(model => model.nome_perfil, "Nome do perfil")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.nome_perfil)
                </dd>

                <dt>
                    @Html.LabelFor(model => model.descricao_perfil, "Descrição do perfil")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.descricao_perfil)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Editar", "Edit", new { id = Model.id_perfil }) |
            @Html.ActionLink("Voltar à lista", "List")
        </p>
    </div>
</div>

Sisjuri/Views/Perfil/Edit.cshtml
@model Sisjuri.Models.perfil

@{
    ViewBag.Title = "Editar perfil";
}

<h1>Editar</h1>
<div class="row">
    <div class="main-box">
        <h2>Perfil</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.id_perfil)

                <div class="form-group">
                    @Html.LabelFor(model => model.nome_perfil, "Nome do perfil", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.nome_perfil, new { size = 30, maxlength = 30 })
                        @Html.ValidationMessageFor(model => model.nome_perfil)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.descricao_perfil, "Descrição do perfil", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.descricao_perfil, new { cols = 50, rows = 4 })
                        @Html.ValidationMessageFor(model => model.descricao_perfil)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Salvar" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        <div>
            @Html.ActionLink("Voltar à lista", "List")
        </div>
    </div>
</div>

Sisjuri/Views/Perfil/Index.cshtml
@model Sisjuri.Models.perfil

@{
    ViewBag.Title = "Pesquisar perfis";
}

<h1>Pesquisar</h1>
<div class="row">
    <div class="main-box">
        <h2>Perfil</h2>

        @using (Html.BeginForm("List", "perfil"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.nome_perfil, "Nome do perfil", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.nome_perfil, new { size = 30, maxlength = 30 })
                        @Html.ValidationMessageFor(model => model.nome_perfil)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Pesquisar" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Voltar à lista", "List")
        </div>
    </div>
</div>

Sisjuri/Views/Perfil/List.cshtml
@model IEnumerable<Sisjuri.Models.perfil> 

@{
    ViewBag.Title = "Lista de perfis";
}

<h1>Lista</h1>
<div class="row">
    <div class="main-box">

        <h2>Perfis</h2>        
        <p>
            @Html.ActionLink("Perquisar perfis" , "Index")
            | @Html.ActionLink("Cadastrar novo perfil", "Create")
        </p>
        <br />
        @{ if (ViewData["message"] != null && ViewData["message"].ToString() != "")
           {
                <div class="alert alert-success fade in">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <i class="fa fa-check-circle fa-fw fa-lg"></i>
                    <strong>@ViewData["message"]</strong>
                </div>
           }
               
        }

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            <span>Nome do perfil</span>
                        </th>
                        <th>
                            <span>Descrição do perfil</span>
                        </th>
                        <th>
                            <span>Ações</span>
                        </th>
                    </tr>
                </thead>

                @foreach (var item in Model)
                {
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.nome_perfil)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.descricao_perfil)
                            </td>

                            <td style="width: 15%;">
                                <a title="Ver detalhes" class="table-link" href="@Url.Action("Details", "Perfil", new { id = item.id_perfil})">
                                    <span class=" fa-stack">
                                    <i class="fa fa-square fa-stack-2x"></i>
                                    <i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                                <a title="Editar" class="table-link primary" href="@Url.Action("Edit", "Perfil", new { id = item.id_perfil})">
                                    <span class="fa-stack">
                                        <i class="fa fa-square fa-stack-2x"></i>
                                        <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                                <a title="Excluir" class="table-link danger" href="@Url.Action("Delete", "Perfil", new { id = item.id_perfil})">
                                    <span class="fa-stack">
                                        <i class="fa fa-square fa-stack-2x"></i>
                                        <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </td>        
                        </tr>
                    </tbody>
                }
            </table>
            <hr />
        </div>
    </div>
</div>