Sisjuri/Models/npj.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisjuri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class npj
    {
        public npj()
        {
            this.juri = new HashSet<juri>();
        }
    
        public int id_npj { get; set; }
        public string nome_npj { get; set; }
        public string telefone_npj { get; set; }
        public string cnpj_npj { get; set; }
        public string endereco_npj { get; set; }
        public int fk_id_faculdade { get; set; }
    
        public virtual faculdade faculdade { get; set; }
        public virtual ICollection<juri> juri { get; set; }
    }
}

Sisjuri/Controllers/NPJController.cs
using Sisjuri.Models;
using Sisjuri.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Sisjuri.Controllers
{
    [Authorize(Roles = "Administrador, Organizador")]
    public class NPJController : BaseController
    {
        FaculdadeRepository _FaculdadeRepository;
        NPJRepository _NPJRepository;

        public FaculdadeRepository FaculdadeRepository
        {
            get {
                if (_FaculdadeRepository == null)
                    _FaculdadeRepository = new FaculdadeRepository();
                return _FaculdadeRepository; }
            set { _FaculdadeRepository = value; }
        }

        public NPJRepository NPJRepository
        {
            get {
                if (_NPJRepository == null)
                    _NPJRepository = new NPJRepository();
                return _NPJRepository; }
            set { _NPJRepository = value; }
        }


        //
        // GET: /NPJ/
        public ActionResult Index()
        {
            return View(new npj());
        }

        public ActionResult List(npj entity, String message, String messageError)
        {
            ViewData["message"] = message;
            ViewData["messageError"] = messageError;
            if (string.IsNullOrEmpty(entity.cnpj_npj) && (string.IsNullOrEmpty(entity.nome_npj)))
            {
                return View(NPJRepository.GetAll());
            }
            else
            {
                return View(NPJRepository.GetAllByCriteria(entity.nome_npj, entity.cnpj_npj));
            }
        }

        //
        // GET: /NPJ/Details/5
        public ActionResult Details(int id)
        {
            return View(NPJRepository.GetOne(id));
        }

        //
        // GET: /NPJ/Create
        public ActionResult Create()
        {
            LoadFormFaculdade(); 
            return View(new npj());
        }

        //
        // POST: /NPJ/Create
        [HttpPost]
        public ActionResult Create(npj npj)
        {
            LoadFormFaculdade(); 

            try
            {
                if (validate(npj))
                    return View(npj);

                NPJRepository.Create(npj);

                return RedirectToAction("List", new { message = "Dados cadastrados com sucesso!" });
            }
            catch
            {
                return View(npj);
            }
        }

        //
        // GET: /NPJ/Edit/5
        public ActionResult Edit(int id)
        {
            LoadFormFaculdade(); 

            return View(NPJRepository.GetOne(id));
        }

        //
        // POST: /NPJ/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, npj npj)
        {
            LoadFormFaculdade(); 

            try
            {
                if (validate(npj))
                    return View(npj);

                NPJRepository.Edit(npj);
                return RedirectToAction("List", new { message = "Dados editados com sucesso!" });
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /NPJ/Delete/5
        public ActionResult Delete(int id)
        {
            return View(NPJRepository.GetOne(id));
        }

        //
        // POST: /NPJ/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, npj npj)
        {
            try
            {
                npj = NPJRepository.GetOne(id);

                if (npj.juri.Count > 0)
                    return RedirectToAction("List", new { messageError = "Esse NPJ possui registros vinculados a seu cadastro. Não é possível excluí-lo." });

                NPJRepository.Delete(npj);

                return RedirectToAction("List", new { message = "Dados excluídos com sucesso!" });
            }
            catch
            {
                return View();
            }
        }

        public bool validate(npj entity)
        {
            bool retorno = false;

            if (string.IsNullOrEmpty(entity.nome_npj))
            {
                ModelState.AddModelError("nome_npj", "Campo obrigatório");
                retorno = true;
            }
            if (string.IsNullOrEmpty(entity.cnpj_npj))
            {
                ModelState.AddModelError("cnpj_npj", "Campo obrigatório");
                retorno = true;
            }
            if (!ValidaCNPJ(entity.cnpj_npj))
            {
                ModelState.AddModelError("cnpj_npj", "CNPJ inválido");
                retorno = true;
            }
            if (string.IsNullOrEmpty(entity.endereco_npj))
            {
                ModelState.AddModelError("endereco_npj", "Campo obrigatório");
                retorno = true;
            }
            if (string.IsNullOrEmpty(entity.telefone_npj))
            {
                ModelState.AddModelError("telefone_npj", "Campo obrigatório");
                retorno = true;
            }

            return retorno;
        }

        public bool ValidaCNPJ(string vrCNPJ)
        {

            string CNPJ = vrCNPJ.Replace(".", "");
            CNPJ = CNPJ.Replace("/", "");
            CNPJ = CNPJ.Replace("-", "");

            int[] digitos, soma, resultado;
            int nrDig;
            string ftmt;
            bool[] CNPJOk;

            ftmt = "6543298765432";
            digitos = new int[14];
            soma = new int[2];
            soma[0] = 0;
            soma[1] = 0;
            resultado = new int[2];
            resultado[0] = 0;
            resultado[1] = 0;
            CNPJOk = new bool[2];
            CNPJOk[0] = false;
            CNPJOk[1] = false;

            try
            {
                for (nrDig = 0; nrDig < 14; nrDig++)
                {
                    digitos[nrDig] = int.Parse(
                     CNPJ.Substring(nrDig, 1));
                    if (nrDig <= 11)
                        soma[0] += (digitos[nrDig] *
                        int.Parse(ftmt.Substring(
                          nrDig + 1, 1)));
                    if (nrDig <= 12)
                        soma[1] += (digitos[nrDig] *
                        int.Parse(ftmt.Substring(
                          nrDig, 1)));
                }

                for (nrDig = 0; nrDig < 2; nrDig++)
                {
                    resultado[nrDig] = (soma[nrDig] % 11);
                    if ((resultado[nrDig] == 0) || (resultado[nrDig] == 1))
                        CNPJOk[nrDig] = (
                        digitos[12 + nrDig] == 0);

                    else
                        CNPJOk[nrDig] = (
                        digitos[12 + nrDig] == (
                        11 - resultado[nrDig]));

                }

                return (CNPJOk[0] && CNPJOk[1]);

            }
            catch
            {
                return false;
            }

        }

        public void LoadFormFaculdade()
        {
            IEnumerable<faculdade> lst = FaculdadeRepository.GetAll();
            int c = lst.Count();
            ViewData["lstFaculdade"] = lst;
        }
    }
}

Sisjuri/Views/NPJ/Create.cshtml
@model Sisjuri.Models.npj

@{
    ViewBag.Title = "Cadastrar NPJ";
}

<div class="row">
    <div class="main-box">
        <h2>Cadastrar NPJ</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.nome_npj, "Nome do NPJ", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.nome_npj, new { size = 30, maxlength = 45 })
                        @Html.ValidationMessageFor(model => model.nome_npj)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.cnpj_npj, "CNPJ", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.cnpj_npj, new { id = "cnpj", size = 20, maxlength = 18 })
                        @Html.ValidationMessageFor(model => model.cnpj_npj)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.endereco_npj, "Endereço", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.endereco_npj, new { size = 40, maxlength = 60 })
                        @Html.ValidationMessageFor(model => model.endereco_npj)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.telefone_npj, "Telefone", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.telefone_npj, new { id = "telefoneold", size = 20, maxlength = 15 })
                        @Html.ValidationMessageFor(model => model.telefone_npj)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.fk_id_faculdade, "Faculdade", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.fk_id_faculdade, new SelectList(ViewData["lstFaculdade"] as System.Collections.IEnumerable, "id_faculdade", "nome_faculdade"))
                        @Html.ValidationMessageFor(model => model.fk_id_faculdade)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Cadastrar" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        <div>
            @Html.ActionLink("Cancelar", "List")
        </div>
    </div>
</div>

Sisjuri/Views/NPJ/Delete.cshtml
@model Sisjuri.Models.npj

@{
    ViewBag.Title = "Excluir NPJ";
}

<div class="row">
    <div class="main-box">
        <h2>Tem certeza que deseja excluir este NPJ?</h2>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.LabelFor(model => model.nome_npj, "Nome do NPJ")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.nome_npj)
                </dd>

                <dt>
                    @Html.LabelFor(model => model.cnpj_npj, "CNPJ")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.cnpj_npj)
                </dd>

                <dt>
                    @Html.LabelFor(model => model.endereco_npj, "Endereço")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.endereco_npj)
                </dd>

                <dt>
                    @Html.LabelFor(model => model.telefone_npj, "Telefone")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.telefone_npj)
                </dd>
                <dt>
                    @Html.LabelFor(model => model.faculdade.nome_faculdade, "Pertence a")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.faculdade.nome_faculdade)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Excluir" class="btn btn-default" /> |
                    @Html.ActionLink("Voltar à lista", "List")
                </div>
            }
        </div>
    </div>
</div>

Sisjuri/Views/NPJ/Details.cshtml
@model Sisjuri.Models.npj

@{
    ViewBag.Title = "Detalhes";
}

<div class="row">
    <div class="main-box">
        <h2>Detalhes do NPJ</h2>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.LabelFor(model => model.nome_npj, "Nome do NPJ")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.nome_npj)
                </dd>

                <dt>
                    @Html.LabelFor(model => model.cnpj_npj, "CNPJ")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.cnpj_npj)
                </dd>

                <dt>
                    @Html.LabelFor(model => model.endereco_npj, "Endereço")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.endereco_npj)
                </dd>

                <dt>
                    @Html.LabelFor(model => model.telefone_npj, "Telefone")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.telefone_npj)
                </dd>
                <dt>
                    @Html.LabelFor(model => model.faculdade.nome_faculdade, "Pertence a")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.faculdade.nome_faculdade)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Editar", "Edit", new { id = Model.id_npj }) |
            @Html.ActionLink("Voltar à lista", "List")
        </p>
    </div>
</div>

Sisjuri/Views/NPJ/Edit.cshtml
@model Sisjuri.Models.npj

@{
    ViewBag.Title = "Editar NPJ";
}

<div class="row">
    <div class="main-box">
        <h2>Editar NPJ</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.fk_id_faculdade)
                @Html.HiddenFor(model => model.id_npj)

                <div class="form-group">
                    @Html.LabelFor(model => model.nome_npj, "Nome do NPJ", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.nome_npj, new { size = 30, maxlength = 45 })
                        @Html.ValidationMessageFor(model => model.nome_npj)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.cnpj_npj, "CNPJ", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.cnpj_npj, new { id = "cnpj", size = 20, maxlength = 18 })
                        @Html.ValidationMessageFor(model => model.cnpj_npj)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.endereco_npj, "Endereço", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.endereco_npj, new { size = 40, maxlength = 60 })
                        @Html.ValidationMessageFor(model => model.endereco_npj)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.telefone_npj, "Telefone", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.telefone_npj, new { id = "telefoneold", size = 20, maxlength = 15 })
                        @Html.ValidationMessageFor(model => model.telefone_npj)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.fk_id_faculdade, "Faculdade", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.fk_id_faculdade, new SelectList(ViewData["lstFaculdade"] as System.Collections.IEnumerable, "id_faculdade", "nome_faculdade"))
                        @Html.ValidationMessageFor(model => model.fk_id_faculdade)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Salvar" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        <div>
            @Html.ActionLink("Cancelar", "List")
        </div>
    </div>
</div>

Sisjuri/Views/NPJ/Index.cshtml
@model Sisjuri.Models.npj

@{
    ViewBag.Title = "Pesquisar NPJs";
}

<div class="row">
    <div class="main-box">
        <h2>Pesquisar NPJ</h2>

        @using (Html.BeginForm("List", "npj"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.nome_npj, "Nome do NPJ", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.nome_npj, new { size = 30, maxlength = 45 })
                        @Html.ValidationMessageFor(model => model.nome_npj)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.cnpj_npj, "CNPJ", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.cnpj_npj, new { id = "cnpj", size = 20, maxlength = 18 })
                        @Html.ValidationMessageFor(model => model.cnpj_npj)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Pesquisar" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        <div>
            @Html.ActionLink("Voltar à lista", "List")
        </div>
    </div>
</div>

Sisjuri/Views/NPJ/List.cshtml
@model IEnumerable<Sisjuri.Models.npj>

@{
    ViewBag.Title = "Lista de NPJs";
}

<div class="row">
    <div class="main-box">

        <h2>Lista de NPJs</h2>
        <p>
            @Html.ActionLink("Perquisar NPJs", "Index")
            | @Html.ActionLink("Cadastrar novo NPJ", "Create")
        </p>
        <br />
        @{ if (ViewData["message"] != null && ViewData["message"].ToString() != "")
         {
            <div class="alert alert-success fade in">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <i class="fa fa-check-circle fa-fw fa-lg"></i>
                <strong>@ViewData["message"]</strong>
            </div>
         }
         if (ViewData["messageError"] != null && ViewData["messageError"].ToString() != "")
         {
            <div class="alert alert-danger fade in">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <i class="fa fa-times-circle fa-fw fa-lg"></i>
                <strong>@ViewData["messageError"]</strong>
            </div>
         }

        }

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            <span>Nome do NPJ</span>
                        </th>
                        <th>
                            <span>CNPJ</span>
                        </th>
                        <th>
                            <span>Endereço</span>
                        </th>
                        <th>
                            <span>Telefone</span>
                        </th>
                        <th>
                            <span>Ações</span>
                        </th>
                    </tr>
                </thead>

                @foreach (var item in Model)
                {
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.nome_npj)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.cnpj_npj)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.endereco_npj)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.telefone_npj)
                            </td>
                            <td style="width: 15%;">
                                <a title="Ver detalhes" class="table-link" href="@Url.Action("Details", "NPJ", new { id = item.id_npj})">
                                    <span class=" fa-stack">
                                        <i class="fa fa-square fa-stack-2x"></i>
                                        <i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                                <a title="Editar" class="table-link primary" href="@Url.Action("Edit", "NPJ", new { id = item.id_npj })">
                                    <span class="fa-stack">
                                        <i class="fa fa-square fa-stack-2x"></i>
                                        <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                                <a title="Excluir" class="table-link danger" href="@Url.Action("Delete", "NPJ", new { id = item.id_npj })">
                                    <span class="fa-stack">
                                        <i class="fa fa-square fa-stack-2x"></i>
                                        <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                }
            </table>
            <hr />
        </div>
    </div>
</div>