Sisjuri/Models/foto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisjuri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foto
    {
        public int id_foto { get; set; }
        public string path { get; set; }
        public int fk_id_juri { get; set; }
    
        public virtual juri juri { get; set; }
    }
}

Sisjuri/Controllers/FotoController.cs
using Sisjuri.Helpers;
using Sisjuri.Models;
using Sisjuri.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sisjuri.Controllers
{
    [Authorize(Roles = "Administrador, Organizador, Professor, Aluno")]
    public class FotoController : BaseController
    {
        JuriRepository _JuriRepository;
        FotoRepository _FotoRepository;

        public JuriRepository JuriRepository
        {
            get
            {
                if (_JuriRepository == null)
                    _JuriRepository = new JuriRepository();
                return _JuriRepository;
            }
            set { _JuriRepository = value; }
        }

        public FotoRepository FotoRepository
        {
            get {
                if (_FotoRepository == null)
                    _FotoRepository = new FotoRepository();
                return _FotoRepository; }
            set { _FotoRepository = value; }
        }

        //Pesquisar fotos
        // GET: /Documento/
        [Authorize(Roles = "Administrador, Organizador, Professor, Aluno")]
        public ActionResult Index()
        {
            LoadFormJuri();
            return View(new foto());
        }

        //Álbum de fotos
        // Foto/List
        [Authorize(Roles = "Administrador, Organizador, Professor, Aluno")]
        public ActionResult List(foto entity, String message, int idJuri = 0)
        {
            ViewData["message"] = message;
            ViewData["Juri"] = entity.juri;
            ViewData["idFoto"] = entity.id_foto;

            if (idJuri == 0)
            {
                idJuri = entity.fk_id_juri;
                ViewData["idJuri"] = entity.fk_id_juri;
            }
            else
            {
                ViewData["idJuri"] = idJuri;
            }

            var imagesModel = new ImageGallery();

            if (Directory.Exists(Server.MapPath("~/Documentos/Fotos/" + idJuri)))
            {
                var imageFiles = Directory.GetFiles(Server.MapPath("~/Documentos/Fotos/" + idJuri));
                foreach (var item in imageFiles)
                {
                    if (item.IndexOf("Thumbs.db") < 0)
                    imagesModel.ImageList.Add(Path.GetFileName(item));
                }
            }

            return View(imagesModel);
        }

        //
        // GET: /Foto/Create
        [Authorize(Roles = "Administrador, Organizador")]
        public ActionResult UploadImage(int idJuri)
        {
            Session["idJuri"] = idJuri;
            return View();
        }

        //
        // POST: /Foto/Create
        [Authorize(Roles = "Administrador, Organizador")]
        [HttpPost]
        public ActionResult UploadImage(foto foto)
        {
            if (Request.Files.Count != 0)
            {
                if (!Directory.Exists(Server.MapPath("~/Documentos/Fotos/" + Session["idJuri"])))
                {
                    Directory.CreateDirectory(Server.MapPath("~/Documentos/Fotos/" + Session["idJuri"]));
                }
                if (validate(foto)){
                    return View(foto);
                }

                HttpFileCollectionBase hfc = Request.Files;
                List<foto> fotos = new List<foto>();

                for (int i = 0; i < hfc.Count; i++)
                {
                    HttpPostedFileBase file = hfc[i];
                    int fileSize = file.ContentLength;
                    string fileName = file.FileName;

                    file.SaveAs(Server.MapPath("~/Documentos/Fotos/" + Session["idJuri"] + "/" + fileName));

                    ImageGallery imageGallery = new ImageGallery();
                    imageGallery.ID = Guid.NewGuid();
                    imageGallery.Name = fileName;
                    imageGallery.ImagePath = "~/Documentos/Fotos/" + Session["idJuri"] + "/" + fileName;

                    foto salvafoto = new foto();
                    salvafoto.fk_id_juri = int.Parse(Session["idJuri"].ToString());
                    salvafoto.path = imageGallery.ImagePath;
                    fotos.Add(salvafoto);
                }

                FotoRepository.Create(fotos);
                return RedirectToAction("List", new { message = "Fotos publicadas com sucesso!", idJuri = int.Parse(Session["idJuri"].ToString()) });
            }

            return View(foto);
        }

        //
        // GET: /Foto/Delete/5
        [Authorize(Roles = "Administrador, Organizador")]
        public ActionResult Delete(string path)
        {
            return View(FotoRepository.GetOne(path));
        }

        //
        // POST: /Foto/Delete/5
        [Authorize(Roles = "Administrador, Organizador")]
        [HttpPost]
        public ActionResult Delete(string path, foto foto)
        {
            try
            {
                foto = FotoRepository.GetFotoById(path);

                if (!FileServerHelper.DeleteFile(Server.MapPath(foto.path)))
                {
                    throw new Exception("Não foi possível salvar o arquivo");
                }
                else
                {
                    FotoRepository.Delete(foto);
                }

                return RedirectToAction("List", new { message = "Dados excluídos com sucesso!" });
            }
            catch
            {
                return View();
            }
        }


        public void LoadFormJuri()
        {
            IEnumerable<juri> lst = JuriRepository.GetAll();
            int c = lst.Count();
            ViewData["lstJuri"] = lst;
        }

        public bool validate(foto entity)
        {
            bool retorno = false;

            if (string.IsNullOrEmpty(entity.path))
            {
                ModelState.AddModelError("path", "Escolha uma ou mais fotos para publicar.");
                retorno = true;
            }

            return retorno;
        }


    }
}

Sisjuri/Views/Foto/Delete.cshtml
@model Sisjuri.Models.foto

@{
    ViewBag.Title = "Excluir foto";
}

<div class="row">
    <div class="main-box">
        <h2>Tem certeza que deseja excluir esta foto?</h2>
        <div>
            <hr />
            <dl class="dl-horizontal">

            </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Excluir" class="btn btn-default" /> |
                        @Html.ActionLink("Cancelar", "List")
                    </div>
                }
        </div>
    </div>
</div>

Sisjuri/Views/Foto/Index.cshtml
@model Sisjuri.Models.foto

@{
    ViewBag.Title = "Pesquisar fotos";
}

<div class="row">
    <div class="main-box">
        <h2>Pesquisar fotos</h2>

        @using (Html.BeginForm("List", "foto"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.fk_id_juri, "Júri simulado", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.fk_id_juri, new SelectList(ViewData["lstJuri"] as System.Collections.IEnumerable, "id_juri", "nome_juri"))
                        @Html.ValidationMessageFor(model => model.fk_id_juri)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Pesquisar" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Sisjuri/Views/Foto/List.cshtml
@model Sisjuri.Models.ImageGallery

@{
    Sisjuri.Models.usuario user = ((Sisjuri.Models.usuario)Session["usuario"]);
    ViewBag.Title = "Fotos";
}

    <div class="row">
        <div class="main-box">

            <h2>Fotos do júri simulado</h2>
            <p>
                @Html.ActionLink("Pesquisar fotos", "Index") |
                @{if (user.fk_id_perfil == 1 || user.fk_id_perfil == 2)
            {
                @Html.ActionLink("Publicar fotos", "UploadImage", new { idJuri = ViewData["idJuri"] })
            }}
            </p>
            <br />
            @{ if (ViewData["message"] != null && ViewData["message"].ToString() != "")
            {
            <div class="alert alert-success fade in">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <i class="fa fa-check-circle fa-fw fa-lg"></i>
                    <strong>@ViewData["message"]</strong>
                </div>
            }

            }

            <div id="gallery-photos-wrapper">
                <div id="gallery-photos" class="clearfix ui-sortable">
                    @foreach (var item in Model.ImageList)
                    {
                        <div class="col-md-3 col-sm-3 col-xs-6" style="text-align:center">
                            <a class="fancybox" rel="gallery1" href="@Url.Content("~/Documentos/Fotos/" + ViewData["idJuri"] + "/" + item)">
                                <div id="fancybox" class=""> @*Quando não tinha a 1ª DIV do foreach o col-md-3 col-sm-3 col-xs-6 ficava nessa DIV*@
                                    <div class="fancybox-image">
                                        <img class="fancybox-image" src="@Url.Content("~/Documentos/Fotos/" + ViewData["idJuri"] + "/" + item)">
                                    </div>
                                </div>
                            </a>
                            @{if (user.fk_id_perfil == 1 || user.fk_id_perfil == 2)
                            {
                                  
                            <a title="Excluir" style="color: #fe635f" href="@Url.Action("Delete", "Foto", new { path = "~/Documentos/Fotos/" + ViewData["idJuri"] + "/" + item })">
                                <span class="fa-stack" style="padding-bottom: 40px">
                                    <i class="fa fa-square fa-stack-2x"></i>
                                    <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                            }}

                        </div>
                    }
                </div>
            <hr />
            </div>
        </div>
</div>

Sisjuri/Views/Foto/UploadImage.cshtml
@using Sisjuri.Helpers;

@model Sisjuri.Models.foto

@{
    ViewBag.Title = "Publicar fotos";
}

<div class="row">
    <div class="main-box">
        <h2>Publicar fotos</h2>

        @using (Html.BeginForm("UploadImage", "Foto", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "Checkfiles(this)"}))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @{ if (ViewData["message"] != null && ViewData["message"].ToString() != "")
                 {
                    <div class="alert alert-danger fade in">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <i class="fa fa-check-circle fa-fw fa-lg"></i>
                        <strong>@ViewData["message"]</strong>
                    </div>
                 }

                }
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.path, "Selecione as fotos", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.FileBox("path", new { id = "image", style = string.Format("width:{0}px", 400), accept = "image/png, image/jpeg, image/gif" , multiple = "multiple"})
                        @Html.ValidationMessageFor(model => model.path)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Publicar fotos" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        <div>
            @Html.ActionLink("Cancelar", "List", new { idJuri = int.Parse(Session["idJuri"].ToString()) })
        </div>
    </div>
</div>